#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# The Linux is already installed
# as Ubuntu                     # L
cookbook 'apache2', '~> 3.1.0'  # A
cookbook 'mysql', '~> 6.1.2'    # M
cookbook 'php', '~> 1.7.2'      # P

# And we now have a LAMPstack
# Who needs XAMPP after all
